/********************************************************/
/*****   NAME : Asmaa     ***/
/*****   Date : 6/1/2021  ***/
/*****Version : 1.0 V     ***/
/*****SWC     : DIO       ***/
/********************************************************/

#ifndef DIO_CONFIG_H
#define DIO_CONFIG_H

/*clock frequency*/
#define   F_CPU    8000000UL

/*include micro librarys */

#include <util/delay.h>

/*macros for initial directions */
/*options :
         1- DIO_U8_INITIAL_OUTPUT
		 2- DIO_U8_INITIAL_INPUT*/
#define  DIO_U8_PA0_DIRECTION     DIO_U8_INITIAL_INPUT
#define  DIO_U8_PA1_DIRECTION     DIO_U8_INITIAL_OUTPUT
#define  DIO_U8_PA2_DIRECTION     DIO_U8_INITIAL_OUTPUT
#define  DIO_U8_PA3_DIRECTION     DIO_U8_INITIAL_OUTPUT
#define  DIO_U8_PA4_DIRECTION     DIO_U8_INITIAL_OUTPUT
#define  DIO_U8_PA5_DIRECTION     DIO_U8_INITIAL_OUTPUT
#define  DIO_U8_PA6_DIRECTION     DIO_U8_INITIAL_OUTPUT
#define  DIO_U8_PA7_DIRECTION     DIO_U8_INITIAL_INPUT

/*macros for initial directions for PORTB*/
#define  DIO_U8_PB0_DIRECTION     DIO_U8_INITIAL_INPUT
#define  DIO_U8_PB1_DIRECTION     DIO_U8_INITIAL_INPUT
#define  DIO_U8_PB2_DIRECTION     DIO_U8_INITIAL_INPUT
#define  DIO_U8_PB3_DIRECTION     DIO_U8_INITIAL_INPUT
#define  DIO_U8_PB4_DIRECTION     DIO_U8_INITIAL_OUTPUT
#define  DIO_U8_PB5_DIRECTION     DIO_U8_INITIAL_OUTPUT
#define  DIO_U8_PB6_DIRECTION     DIO_U8_INITIAL_OUTPUT
#define  DIO_U8_PB7_DIRECTION     DIO_U8_INITIAL_OUTPUT


/*macros for initial directions for PORTC*/
#define  DIO_U8_PC0_DIRECTION     DIO_U8_INITIAL_INPUT
#define  DIO_U8_PC1_DIRECTION     DIO_U8_INITIAL_INPUT
#define  DIO_U8_PC2_DIRECTION     DIO_U8_INITIAL_INPUT
#define  DIO_U8_PC3_DIRECTION     DIO_U8_INITIAL_INPUT
#define  DIO_U8_PC4_DIRECTION     DIO_U8_INITIAL_INPUT
#define  DIO_U8_PC5_DIRECTION     DIO_U8_INITIAL_INPUT
#define  DIO_U8_PC6_DIRECTION     DIO_U8_INITIAL_INPUT
#define  DIO_U8_PC7_DIRECTION     DIO_U8_INITIAL_INPUT


/*macros for initial directions for PORTD*/
#define  DIO_U8_PD0_DIRECTION     DIO_U8_INITIAL_INPUT
#define  DIO_U8_PD1_DIRECTION     DIO_U8_INITIAL_INPUT
#define  DIO_U8_PD2_DIRECTION     DIO_U8_INITIAL_INPUT
#define  DIO_U8_PD3_DIRECTION     DIO_U8_INITIAL_INPUT
#define  DIO_U8_PD4_DIRECTION     DIO_U8_INITIAL_INPUT
#define  DIO_U8_PD5_DIRECTION     DIO_U8_INITIAL_INPUT
#define  DIO_U8_PD6_DIRECTION     DIO_U8_INITIAL_INPUT
#define  DIO_U8_PD7_DIRECTION     DIO_U8_INITIAL_INPUT
/*options for initial values:
                   1-DIO_U8_OUTPUT_HIGH
				   2-DIO_U8_OUTPUT_LOW
				   3-DIO_U8_INPUT_FLOATING
				   4-DIO_U8_INPUT_PULLUP*/
#define  DIO_U8_PA0_INITIAL_VALUE      DIO_U8_OUTPUT_LOW
#define  DIO_U8_PA1_INITIAL_VALUE      DIO_U8_OUTPUT_LOW
#define  DIO_U8_PA2_INITIAL_VALUE      DIO_U8_OUTPUT_LOW
#define  DIO_U8_PA3_INITIAL_VALUE      DIO_U8_OUTPUT_LOW
#define  DIO_U8_PA4_INITIAL_VALUE      DIO_U8_OUTPUT_LOW
#define  DIO_U8_PA5_INITIAL_VALUE      DIO_U8_OUTPUT_LOW
#define  DIO_U8_PA6_INITIAL_VALUE      DIO_U8_OUTPUT_LOW
#define  DIO_U8_PA7_INITIAL_VALUE      DIO_U8_OUTPUT_LOW
                          
						  
#define  DIO_U8_PB0_INITIAL_VALUE      DIO_U8_INPUT_FLOATING
#define  DIO_U8_PB1_INITIAL_VALUE      DIO_U8_INPUT_FLOATING
#define  DIO_U8_PB2_INITIAL_VALUE      DIO_U8_INPUT_FLOATING
#define  DIO_U8_PB3_INITIAL_VALUE      DIO_U8_INPUT_FLOATING
#define  DIO_U8_PB4_INITIAL_VALUE      DIO_U8_OUTPUT_HIGH
#define  DIO_U8_PB5_INITIAL_VALUE      DIO_U8_OUTPUT_HIGH
#define  DIO_U8_PB6_INITIAL_VALUE      DIO_U8_OUTPUT_HIGH
#define  DIO_U8_PB7_INITIAL_VALUE      DIO_U8_OUTPUT_HIGH
                           
						   
#define  DIO_U8_PC0_INITIAL_VALUE      DIO_U8_INPUT_FLOATING
#define  DIO_U8_PC1_INITIAL_VALUE      DIO_U8_INPUT_FLOATING
#define  DIO_U8_PC2_INITIAL_VALUE      DIO_U8_INPUT_FLOATING
#define  DIO_U8_PC3_INITIAL_VALUE      DIO_U8_INPUT_FLOATING
#define  DIO_U8_PC4_INITIAL_VALUE      DIO_U8_INPUT_FLOATING
#define  DIO_U8_PC5_INITIAL_VALUE      DIO_U8_INPUT_FLOATING
#define  DIO_U8_PC6_INITIAL_VALUE      DIO_U8_INPUT_FLOATING
#define  DIO_U8_PC7_INITIAL_VALUE      DIO_U8_INPUT_FLOATING
                                 
								 
#define  DIO_U8_PD0_INITIAL_VALUE      DIO_U8_INPUT_FLOATING
#define  DIO_U8_PD1_INITIAL_VALUE      DIO_U8_INPUT_FLOATING
#define  DIO_U8_PD2_INITIAL_VALUE      DIO_U8_INPUT_PULLUP
#define  DIO_U8_PD3_INITIAL_VALUE      DIO_U8_INPUT_PULLUP
#define  DIO_U8_PD4_INITIAL_VALUE      DIO_U8_INPUT_PULLUP
#define  DIO_U8_PD5_INITIAL_VALUE      DIO_U8_INPUT_PULLUP
#define  DIO_U8_PD6_INITIAL_VALUE      DIO_U8_INPUT_FLOATING
#define  DIO_U8_PD7_INITIAL_VALUE      DIO_U8_INPUT_FLOATING







#endif
